version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: easymoto-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easymoto
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"