services:
  - type: web
    name: easymoto-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
